### ISSUE TITLE
Visual cue / badge problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/software-artifact-analyzer#148] opened 2024-07-16 17:24 UTC
This is a continuation of https://github.com/iVis-at-Bilkent/software-artifact-analyzer/issues/140.
- [x] 1. We somehow lost badge **tooltips** (none shows now).
- [x] 2. Since we now aim to show both the anomaly badges and graph theoretical ones together, why not show the anomaly ones on the right side **all the time** (rather than moving them when there is a conflict)?
- [x] 3. Why did we need to treat the size of anomaly badges differently? It results in weird situations like below. I think let's keep the default behavior.
<img width="846" alt="Screenshot 2024-07-16 at 13 22 54" src="https://github.com/user-attachments/assets/239cad74-dd79-49b6-bc25-75389501a8cb">

**Comment by LaraMerdol** [comment] 2024-07-18 21:42
Subtask-1 is fixed. The issue was related to the z-index of the badges. It is now fixed to stay behind the context menu but still ensure the visibility of the tooltip.
<img width="406" alt="Screen Shot 2024-07-19 at 00 42 03" src="https://github.com/user-attachments/assets/7983a54a-1b17-4a27-8afa-9270801371c9">

**Comment by LaraMerdol** [comment] 2024-07-19 07:33
Sub task 2: Now, the Anomaly badge is always positioned on the right, slightly below, to avoid overlapping with the theoretical property badges.
![Screen Recording 2024-07-19 at 10 32 15](https://github.com/user-attachments/assets/34017bf2-5e6a-4267-9f3b-34824bf90e1a)

**Comment by LaraMerdol** [comment] 2024-07-19 07:40
Subtask3:
One reason we treat anomaly badges differently is that if we did not change the size of anomaly badges, they would not be scaled according to the size of the node. Then, for some cases if the theoretical property is too high or too low, it will not be aesthetic. ** I have changed it so that it does not give weird changes now.**
Furthermore, the default behavior for issue type badges is not valid because issue badges provide badge images, and we can automatically adjust their size. Anomaly badges also change size according to the number of anomalies they have. In normal cases, they are displayed as spans, not images.
![Screen Recording 2024-07-19 at 10 37 26](https://github.com/user-attachments/assets/18515a8c-a641-4f93-8b41-ce49627ef8a5)

**Comment by ugurdogrusoz** [comment] 2024-07-19 17:43
@LaraMerdol I can't properly test this since I keep getting DB errors on graph theoretic property operations. Typical scenario to reproduce:
- Sample Data
- Check Anamolies
- Any graph-theoretic property calculation
I think it goes into some kind of an infinite loop or takes too long to finish, often resulting with a DB error.

**Comment by LaraMerdol** [comment] 2024-07-19 19:29
Subtask-1:
Z-index also changed for the issue badges
![Screen Shot 2024-07-19 at 22 29 33](https://github.com/user-attachments/assets/001c27c6-bfb2-4f17-935d-52f655bf05f4)

**Comment by LaraMerdol** [comment] 2024-07-19 19:33
> @LaraMerdol I can't properly test this since I keep getting DB errors on graph theoretic property operations. Typical scenario to reproduce:
> 
> * Sample Data
> * Check Anamolies
> * Any graph-theoretic property calculation
>   I think it goes into some kind of an infinite loop or takes too long to finish, often resulting with a DB error.
This behavior is not visible on local deployment, but I have also encountered it when repeating the above steps and having multiple issue nodes on the canvas in the server.

**Comment by LaraMerdol** [comment] 2024-07-19 19:55
The reason for the issue was that, in some cases, the addIssueBadges and addAnomalyCues function was called more than once. The function execution has been modified. The reason for the loading in some cases when generating anomaly badges is that one query is run for each issue, so it is normal to see this if the graph has too many issues. However, now the detection of anomalies and creation of anomaly badges after theoretical properties take a similar time and do not create DB errors in my computer. 
![Screen Recording 2024-07-19 at 22 54 02](https://github.com/user-attachments/assets/1ecddd31-6fda-44e3-a4b9-4ae2b6fdb755)

**Comment by ugurdogrusoz** [comment] 2024-07-19 20:13
Looks good except:
- Calculate a graph theoretic value
- Show anomaly badges
- Remove highlights
- Now calculate a graph theoretic value again and anomaly badges reappear for no reason

**Comment by LaraMerdol** [comment] 2024-07-22 09:18
> Looks good except:
> 
> * Calculate a graph theoretic value
> * Show anomaly badges
> * Remove highlights
> * Now calculate a graph theoretic value again and anomaly badges reappear for no reason

Reason for the issue is that I forgot to remove the class after removing highlights. Now it is fixed.

**Closed** 2024-07-23 18:39 UTC
